--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_ASSETTYPES
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_ASSETTYPES" 
   (	"ASSETTYPEID" RAW(16), 
	"NAME" VARCHAR2(4000 CHAR), 
	"COMPONENTTYPEID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "AUTOHAUL"."EWMS_ASSETTYPES"."ASSETTYPEID" IS 'A globally unique identifier suitable for use in an occasionally connected distributed system as well as a local database.';
   COMMENT ON COLUMN "AUTOHAUL"."EWMS_ASSETTYPES"."NAME" IS 'The name of this asset type e.g. EVO, DASH9.';
   COMMENT ON TABLE "AUTOHAUL"."EWMS_ASSETTYPES"  IS 'The definition of a major asset type in a system. Major asset types have a defined asset structure which can
be used as the basis for the creation of a sub-asset hierarchy for that major asset.';
REM INSERTING into AUTOHAUL.EWMS_ASSETTYPES
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_ASSETTYPES (ASSETTYPEID,NAME,COMPONENTTYPEID) values ('5E5A5EF724184A48B05553D6E9195348','EVO','7999D34C5843284BB7733EC381A92F20');
Insert into AUTOHAUL.EWMS_ASSETTYPES (ASSETTYPEID,NAME,COMPONENTTYPEID) values ('E458FBFEC3A318408B10A5A63AED8744','DASH9','7999D34C5843284BB7733EC381A92F20');
Insert into AUTOHAUL.EWMS_ASSETTYPES (ASSETTYPEID,NAME,COMPONENTTYPEID) values ('648A2FCF4949B148BC768B290ED92B24','AC','7999D34C5843284BB7733EC381A92F20');
--------------------------------------------------------
--  DDL for Index PK_EWMS_ASSETTYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_ASSETTYPES" ON "AUTOHAUL"."EWMS_ASSETTYPES" ("ASSETTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_ASSETTYPES
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_ASSETTYPES" MODIFY ("ASSETTYPEID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_ASSETTYPES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_ASSETTYPES" ADD CONSTRAINT "PK_EWMS_ASSETTYPES" PRIMARY KEY ("ASSETTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
