--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_COMPONENTENTRIES
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" 
   (	"ENTRYID" RAW(16), 
	"ASSETID" RAW(16), 
	"TIMESTAMP" TIMESTAMP (6), 
	"CONFIGURATIONCODE" VARCHAR2(4000 CHAR), 
	"INPUTPERSON" VARCHAR2(4000 CHAR), 
	"ASSETNUMBER" VARCHAR2(4000 CHAR), 
	"INPUTPERSONNAME" VARCHAR2(4000 CHAR), 
	"INALERT" NUMBER(1,0), 
	"ALERTCOMMENT" VARCHAR2(4000 CHAR), 
	"ALERTTIME" TIMESTAMP (6), 
	"ALERTUSER" VARCHAR2(4000 CHAR), 
	"COMMENTMESSAGE" VARCHAR2(4000 CHAR), 
	"COMMENTUSER" VARCHAR2(4000 CHAR), 
	"COMMENTTIME" TIMESTAMP (6), 
	"ISNOTAPPLICABLE" NUMBER(1,0), 
	"NOTAPPLICABLEUSER" VARCHAR2(4000 CHAR), 
	"NOTAPPLICABLETIME" TIMESTAMP (6), 
	"INSTALLEDBY" VARCHAR2(4000 CHAR), 
	"VERIFIEDBY" VARCHAR2(4000 CHAR), 
	"VALIDATEDBY" VARCHAR2(4000 CHAR), 
	"GENERICVERSION" VARCHAR2(4000 CHAR), 
	"LOCOSPECIFICDATA" VARCHAR2(4000 CHAR), 
	"DOCUMENTTITLE" VARCHAR2(4000 CHAR), 
	"DOCUMENTID" VARCHAR2(4000 CHAR), 
	"DOCUMENTREVISION" VARCHAR2(4000 CHAR), 
	"SOFTWARECONTAINER" VARCHAR2(4000 CHAR), 
	"ENGINEERVALIDATION" VARCHAR2(4000 CHAR), 
	"IMTVALIDATION" VARCHAR2(4000 CHAR), 
	"COMPONENTENTRYDISCRIMINATOR" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUTOHAUL.EWMS_COMPONENTENTRIES
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('5F05E88DEC49D9499A42B541449969A2','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1061:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,'Scott Stephens','Ben Rumbel','Lucas Szmeja','04.00.01.05','N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('839B9C3CAE25A9469C9EDDA8DF90FB4A','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1057:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,'Ben Rumbel','Ben Rumbel','Lucas Szmeja','01.01.07.00','N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('9CD08CC51C20EB45A09765CA3F96860F','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1058:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,'Ben Rumbel','Ben Rumbel','Lucas Szmeja','01.01.07.00','N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('2F744966BDC961418739BAEA3910372C','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1054:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,'N/A','N/A',null,null,'N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('68589B7357EAFA4BA24A3F6F4BBB16AB','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1055:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('568EEF6882C89A40A90207F4AD726008','1FED3DD208DFDE4F839412488DD95878',to_timestamp('16/JUN/17 02:06:54.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1056:SW:0','a','7047','a',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'N/A',null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('2139001A4127C646860D57922B6E6E97','48A65D7E967DB648A7AD8946AB6E4C99',to_timestamp('06/MAY/18 08:17:49.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1076:SW:2','9220296','8193','9220296',null,null,null,null,null,null,null,null,null,null,'Ben Dodson','Jack Garrigan','David Varley','192.168.2.2',null,null,null,null,null,null,null,'1');
Insert into AUTOHAUL.EWMS_COMPONENTENTRIES (ENTRYID,ASSETID,TIMESTAMP,CONFIGURATIONCODE,INPUTPERSON,ASSETNUMBER,INPUTPERSONNAME,INALERT,ALERTCOMMENT,ALERTTIME,ALERTUSER,COMMENTMESSAGE,COMMENTUSER,COMMENTTIME,ISNOTAPPLICABLE,NOTAPPLICABLEUSER,NOTAPPLICABLETIME,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTENTRYDISCRIMINATOR) values ('DD38BDB8C4189443AC962E40A454E254','48A65D7E967DB648A7AD8946AB6E4C99',to_timestamp('06/MAY/18 08:17:51.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),'1075:SW:0','9220296','8193','9220296',null,null,null,null,null,null,null,null,null,null,'Ben Dodson','Jack Garrigan','David Varley','N/A','8193',null,null,null,null,null,null,'1');
--------------------------------------------------------
--  DDL for Index PK_EWMS_COMPONENTENTRIES
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_COMPONENTENTRIES" ON "AUTOHAUL"."EWMS_COMPONENTENTRIES" ("ENTRYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_COMPONENTENTRIES
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("ENTRYID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("ASSETID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("CONFIGURATIONCODE" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("INPUTPERSON" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("ASSETNUMBER" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("INPUTPERSONNAME" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" MODIFY ("COMPONENTENTRYDISCRIMINATOR" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTENTRIES" ADD CONSTRAINT "PK_EWMS_COMPONENTENTRIES" PRIMARY KEY ("ENTRYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
