--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_COMPONENTS
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_COMPONENTS" 
   (	"COMPONENTID" RAW(16), 
	"COMPONENTCLASS" VARCHAR2(4000 CHAR), 
	"NAME" VARCHAR2(4000 CHAR), 
	"COMPONENTSTRUCTUREID" VARCHAR2(4000 CHAR), 
	"INSTALLEDBY" VARCHAR2(4000 CHAR), 
	"VERIFIEDBY" VARCHAR2(4000 CHAR), 
	"VALIDATEDBY" VARCHAR2(4000 CHAR), 
	"HISTORY" VARCHAR2(4000 CHAR), 
	"PARTNUMBER" VARCHAR2(4000 CHAR), 
	"PARTVERSION" VARCHAR2(4000 CHAR), 
	"SERIALNUMBER" VARCHAR2(4000 CHAR), 
	"GENERICVERSION" VARCHAR2(4000 CHAR), 
	"LOCOSPECIFICDATA" VARCHAR2(4000 CHAR), 
	"DOCUMENTTITLE" VARCHAR2(4000 CHAR), 
	"DOCUMENTID" VARCHAR2(4000 CHAR), 
	"DOCUMENTREVISION" VARCHAR2(4000 CHAR), 
	"SOFTWARECONTAINER" VARCHAR2(4000 CHAR), 
	"ENGINEERVALIDATION" VARCHAR2(4000 CHAR), 
	"IMTVALIDATION" VARCHAR2(4000 CHAR), 
	"COMPONENTDISCRIMINATOR" VARCHAR2(4000 CHAR), 
	"COMPONENTTYPEID" RAW(16), 
	"ASSETID" RAW(16), 
	"PARENTCOMPONENTID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "AUTOHAUL"."EWMS_COMPONENTS"."PARTNUMBER" IS 'A unique identifier for the design of a hardware asset by a manufacturer.';
   COMMENT ON COLUMN "AUTOHAUL"."EWMS_COMPONENTS"."PARTVERSION" IS 'A manufacturer supplied version number which identifies which version of a design that an asset was manufactured against.';
   COMMENT ON COLUMN "AUTOHAUL"."EWMS_COMPONENTS"."SERIALNUMBER" IS 'A unique identifier for an individual asset provided by a manufacturer.';
   COMMENT ON COLUMN "AUTOHAUL"."EWMS_COMPONENTS"."GENERICVERSION" IS 'A manufacturer supplied version number which identifies which version of a software design that was installed in the context of an asset.';
REM INSERTING into AUTOHAUL.EWMS_COMPONENTS
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('8BFD0E79B971EA4283D0D7A730989CC0','Software',null,'1056:SW:0',null,null,null,null,null,null,null,null,'N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('10E533DFAAB2454CB42DA047BC181219','Software',null,'1060:SW:0','Dylan Peace','Daniel Hearn','Callum Thwaite',null,null,null,null,'02.01.01.01','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('4F10B3A532F35B429502285D5149DA06','Software',null,'1027:SW:0','N/A','Michael Galatsianos','Callum Thwaite',null,null,null,null,'11.9.4','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('D076491E38C68B4CA2178434C899AB7A','Software',null,'1041:SW:1','Paul Barlow','Adam Ardern','Callum Thwaite',null,null,null,null,'2.05','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('A5EE24FFDA08204792885A09451C7064','Software',null,'1041:SW:2','Paul Barlow','Adam Ardern','Callum Thwaite',null,null,null,null,'2.05','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('604D68A7EB230B4E9E7C71C46C18F6B2','Software',null,'1041:SW:3','Paul Barlow','Adam Ardern','Callum Thwaite',null,null,null,null,'2.05','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('7469020FF7252B44880DCC689E3644C8','Software',null,'1031:SW:1','Ben Rumbel','Michael Galatsianos','Callum Thwaite',null,null,null,null,'1.10_4','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('CF882F0C82344B4A9EF6BA653EE9458C','Software',null,'1032:SW:1','Wade Hill','Wade Hill','Callum Thwaite',null,null,null,null,'1.0_6','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('6B17EC5AB381E847B05BFC41E8E09368','Software',null,'1033:SW:2','Ben Rumbel','Michael Galatsianos','Callum Thwaite',null,null,null,null,'1.10_4','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('AE9C67B4F354D6439EB87269784F5688','Software',null,'1034:SW:3','Ben Rumbel','Michael Galatsianos','Callum Thwaite',null,null,null,null,'1.10_4','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('4FC402DF001B354CAD49A085C4C432A1','Software',null,'1035:SW:2','Wade Hill','Wade Hill','Callum Thwaite',null,null,null,null,'1.0_6','N/A',null,null,null,null,null,null,'SOFTWARE',null,'1FED3DD208DFDE4F839412488DD95878',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('821F2104100F13448E3F0302AF5BD386','Software','Camera Driver Firmware','1078:SW:1','Michael Nelson','Colin Dwyer','Callum Thwaite',null,null,null,null,'5.2.0_BUILD_140721',null,null,null,null,null,null,null,'SOFTWARE',null,'D970671B2A024A4085F32CD0809A1899',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('574207CB14F7C644A10C338BDDD1F72D','Software','Camera Driver Configuration','1077:SW:1','Michael Nelson','Colin Dwyer','Callum Thwaite',null,null,null,null,'RC-2012-IRV4.0',null,null,null,null,null,null,null,'SOFTWARE',null,'D970671B2A024A4085F32CD0809A1899',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('CCB756E2DF85844DADC3B05BE233A2D8','Software','Camera Observer Firmware','1078:SW:2','Michael Nelson','Colin Dwyer','Callum Thwaite',null,null,null,null,'5.2.0_BUILD_140721',null,null,null,null,null,null,null,'SOFTWARE',null,'D970671B2A024A4085F32CD0809A1899',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('CCF060A70180E54E923F310379A77DD3','Software','Camera Observer Configuration','1077:SW:2',null,'Colin Dwyer','Callum Thwaite',null,null,null,null,'RC-2012-IRV4.0',null,null,null,null,null,null,null,'SOFTWARE',null,'D970671B2A024A4085F32CD0809A1899',null);
Insert into AUTOHAUL.EWMS_COMPONENTS (COMPONENTID,COMPONENTCLASS,NAME,COMPONENTSTRUCTUREID,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,HISTORY,PARTNUMBER,PARTVERSION,SERIALNUMBER,GENERICVERSION,LOCOSPECIFICDATA,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATION,COMPONENTDISCRIMINATOR,COMPONENTTYPEID,ASSETID,PARENTCOMPONENTID) values ('76ECDE618D3A5B478CA763AE6A3C09DB','Software','Camera Observer Configuration','1077:SW:2','Michael Nelson',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SOFTWARE',null,'D970671B2A024A4085F32CD0809A1899',null);
--------------------------------------------------------
--  DDL for Index PK_EWMS_COMPONENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_COMPONENTS" ON "AUTOHAUL"."EWMS_COMPONENTS" ("COMPONENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_COMPONENTS
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTS" MODIFY ("COMPONENTID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTS" MODIFY ("COMPONENTDISCRIMINATOR" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_COMPONENTS" ADD CONSTRAINT "PK_EWMS_COMPONENTS" PRIMARY KEY ("COMPONENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
