--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_SWCOMPONENTBASELINES
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" 
   (	"BASELINEID" RAW(16), 
	"CONFIGURATIONITEM" VARCHAR2(4000 CHAR), 
	"COMPONENTID" VARCHAR2(4000 CHAR), 
	"DOCUMENTTITLE" VARCHAR2(4000 CHAR), 
	"DOCUMENTID" VARCHAR2(4000 CHAR), 
	"DOCUMENTREVISION" VARCHAR2(4000 CHAR), 
	"SOFTWARECONTAINER" VARCHAR2(4000 CHAR), 
	"ENGINEERVALIDATION" VARCHAR2(4000 CHAR), 
	"IMTVALIDATIONANDHOSDIUPDATE" VARCHAR2(4000 CHAR), 
	"ROWIDENTIFIER" NUMBER(10,0), 
	"DOCUMENTTITLECOLUMNID" NUMBER(10,0), 
	"DOCUMENTIDCOLUMNID" NUMBER(10,0), 
	"DOCUMENTREVISIONCOLUMNID" NUMBER(10,0), 
	"SOFTWARECONTAINERCOLUMNID" NUMBER(10,0), 
	"ENGINEERVALIDATIONCOLUMNID" NUMBER(10,0), 
	"IMTVALIDATIONCOLUMNID" NUMBER(10,0), 
	"RESETVALUEONLOCALCHANGE1" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE2" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE3" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE4" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE5" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE1" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE2" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE3" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE4" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE5" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE1" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE2" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE3" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE4" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE5" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE6" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE6" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE6" NUMBER(1,0), 
	"NEXTVERSION" RAW(16), 
	"PREVIOUSVERSION" RAW(16), 
	"APPLYGLOBALCHANGES" NUMBER(1,0), 
	"TCRID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUTOHAUL.EWMS_SWCOMPONENTBASELINES
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('64BF274FD4871246BF09254C1D11C2CA',null,null,null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'8721572147B5E64E9219A6E79EABE318',null,1,'E0E8C77A8115EB4BA12ED148C3093643');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('8721572147B5E64E9219A6E79EABE318',null,null,null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'A9FCE52E8920064DA4A1542E70248ABE','64BF274FD4871246BF09254C1D11C2CA',1,'CCA9B1E6BD6017488F96F369184A846C');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('A9FCE52E8920064DA4A1542E70248ABE','Baseline','0200:SW:0',null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'F4A9CE2824DDAD4FA86BC605D8D8A2D3','8721572147B5E64E9219A6E79EABE318',1,'68D93694E254584C802B7D4013622370');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('F4A9CE2824DDAD4FA86BC605D8D8A2D3','Baseline','0200:SW:0',null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'F67A26B89F366D4D8214CB1171F69044','A9FCE52E8920064DA4A1542E70248ABE',1,'B2D032F3DAD0C040BD432C031FA80ABD');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('F67A26B89F366D4D8214CB1171F69044','Baseline','0200:SW:0',null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'5E2F36146142244292053D7D8994B008','F4A9CE2824DDAD4FA86BC605D8D8A2D3',1,'F4AF753F43B52E46A67C3BC7D329C6F4');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('5E2F36146142244292053D7D8994B008','Baseline','0200:SW:0',null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,'DF014154E63CEF4696D8A22BE6AE92E2','F67A26B89F366D4D8214CB1171F69044',1,'9912C5EC80C72E49ADEC9E73C635AFE4');
Insert into AUTOHAUL.EWMS_SWCOMPONENTBASELINES (BASELINEID,CONFIGURATIONITEM,COMPONENTID,DOCUMENTTITLE,DOCUMENTID,DOCUMENTREVISION,SOFTWARECONTAINER,ENGINEERVALIDATION,IMTVALIDATIONANDHOSDIUPDATE,ROWIDENTIFIER,DOCUMENTTITLECOLUMNID,DOCUMENTIDCOLUMNID,DOCUMENTREVISIONCOLUMNID,SOFTWARECONTAINERCOLUMNID,ENGINEERVALIDATIONCOLUMNID,IMTVALIDATIONCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,RESETVALUEONLOCALCHANGE6,RESETVALUEONGLOBALCHANGE6,FORCERESETVALUEONGLOBALCHANGE6,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('DF014154E63CEF4696D8A22BE6AE92E2','Baseline','0200:SW:0',null,null,null,null,null,null,1,1,2,3,4,5,6,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,0,null,'5E2F36146142244292053D7D8994B008',1,'028DBD176836D648B19BD3D423586210');
--------------------------------------------------------
--  DDL for Index PK_EWMS_SWCOMPONENTBASELINES
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_SWCOMPONENTBASELINES" ON "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" ("BASELINEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KEY_EWMS_SWCOMPONE_03956138389
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."KEY_EWMS_SWCOMPONE_03956138389" ON "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" ("TCRID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_SWCOMPONENTBASELINES
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("BASELINEID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("DOCUMENTTITLECOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("DOCUMENTIDCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("DOCUMENTREVISIONCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("SOFTWARECONTAINERCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("ENGINEERVALIDATIONCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("IMTVALIDATIONCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONLOCALCHANGE6" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("RESETVALUEONGLOBALCHANGE6" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("FORCERESETVALUEONGLOBALCHANGE6" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" MODIFY ("APPLYGLOBALCHANGES" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" ADD CONSTRAINT "PK_EWMS_SWCOMPONENTBASELINES" PRIMARY KEY ("BASELINEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTBASELINES" ADD CONSTRAINT "KEY_EWMS_SWCOMPONE_03956138389" UNIQUE ("TCRID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
