--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_SWCOMPONENTTCRS
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" 
   (	"SWCOMPONENTTCRID" RAW(16), 
	"ROWIDENTIFIER" NUMBER(10,0), 
	"CONFIGURATIONITEM" VARCHAR2(4000 CHAR), 
	"COMPONENTID" VARCHAR2(4000 CHAR), 
	"AIMSREFERENCE" VARCHAR2(4000 CHAR), 
	"GENERICVERSION" VARCHAR2(4000 CHAR), 
	"LOCOSPECIFICDATA" VARCHAR2(4000 CHAR), 
	"INSTALLEDBY" VARCHAR2(4000 CHAR), 
	"VERIFIEDBY" VARCHAR2(4000 CHAR), 
	"VALIDATEDBY" VARCHAR2(4000 CHAR), 
	"GENERICVERSIONCOLUMNID" NUMBER(10,0), 
	"LOCOSPECIFICDATACOLUMNID" NUMBER(10,0), 
	"INSTALLEDBYCOLUMNID" NUMBER(10,0), 
	"VERIFIEDBYCOLUMNID" NUMBER(10,0), 
	"VALIDATEDBYCOLUMNID" NUMBER(10,0), 
	"RESETVALUEONLOCALCHANGE1" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE2" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE3" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE4" NUMBER(1,0), 
	"RESETVALUEONLOCALCHANGE5" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE1" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE2" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE3" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE4" NUMBER(1,0), 
	"RESETVALUEONGLOBALCHANGE5" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE1" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE2" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE3" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE4" NUMBER(1,0), 
	"FORCERESETVALUEONGLOBALCHANGE5" NUMBER(1,0), 
	"TCRVERSION" VARCHAR2(4000 CHAR), 
	"NEXTVERSION" RAW(16), 
	"PREVIOUSVERSION" RAW(16), 
	"APPLYGLOBALCHANGES" NUMBER(1,0), 
	"TCRID" RAW(16)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUTOHAUL.EWMS_SWCOMPONENTTCRS
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_SWCOMPONENTTCRS (SWCOMPONENTTCRID,ROWIDENTIFIER,CONFIGURATIONITEM,COMPONENTID,AIMSREFERENCE,GENERICVERSION,LOCOSPECIFICDATA,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSIONCOLUMNID,LOCOSPECIFICDATACOLUMNID,INSTALLEDBYCOLUMNID,VERIFIEDBYCOLUMNID,VALIDATEDBYCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,TCRVERSION,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('DDB403F113234C4E90EE7C68A42CE2A9',16,'CCTE1 - LCVO (VO Block)',null,'N/A',null,'N/A',null,null,null,3,4,5,6,7,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,'01.00','0110BCE3CD2D6B4FA6468E4B145D2400',null,0,'E0E8C77A8115EB4BA12ED148C3093643');
Insert into AUTOHAUL.EWMS_SWCOMPONENTTCRS (SWCOMPONENTTCRID,ROWIDENTIFIER,CONFIGURATIONITEM,COMPONENTID,AIMSREFERENCE,GENERICVERSION,LOCOSPECIFICDATA,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSIONCOLUMNID,LOCOSPECIFICDATACOLUMNID,INSTALLEDBYCOLUMNID,VERIFIEDBYCOLUMNID,VALIDATEDBYCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,TCRVERSION,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('DDB403F113234C4E90EE7C68A42CE2A9',17,'CCTE2 - LCAP (AP Block)',null,'N/A',null,'N/A',null,null,null,3,4,5,6,7,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,'01.00','0110BCE3CD2D6B4FA6468E4B145D2400',null,0,'E0E8C77A8115EB4BA12ED148C3093643');
Insert into AUTOHAUL.EWMS_SWCOMPONENTTCRS (SWCOMPONENTTCRID,ROWIDENTIFIER,CONFIGURATIONITEM,COMPONENTID,AIMSREFERENCE,GENERICVERSION,LOCOSPECIFICDATA,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSIONCOLUMNID,LOCOSPECIFICDATACOLUMNID,INSTALLEDBYCOLUMNID,VERIFIEDBYCOLUMNID,VALIDATEDBYCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,TCRVERSION,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('DDB403F113234C4E90EE7C68A42CE2A9',18,'CCTE2 - LCPL (CPL Block)',null,'N/A',null,'N/A',null,null,null,3,4,5,6,7,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,'01.00','0110BCE3CD2D6B4FA6468E4B145D2400',null,0,'E0E8C77A8115EB4BA12ED148C3093643');
Insert into AUTOHAUL.EWMS_SWCOMPONENTTCRS (SWCOMPONENTTCRID,ROWIDENTIFIER,CONFIGURATIONITEM,COMPONENTID,AIMSREFERENCE,GENERICVERSION,LOCOSPECIFICDATA,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSIONCOLUMNID,LOCOSPECIFICDATACOLUMNID,INSTALLEDBYCOLUMNID,VERIFIEDBYCOLUMNID,VALIDATEDBYCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,TCRVERSION,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('D3A3C84A9A3CD14D90305E4C9F8B2EB5',3,'WiMax Configuration','1092:SW:0','COMM.WMAX-C1',null,'N/A',null,null,null,3,4,5,6,7,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,'04.00',null,'66AC4E3F88E39E4386E25E352B3D8B92',0,'028DBD176836D648B19BD3D423586210');
Insert into AUTOHAUL.EWMS_SWCOMPONENTTCRS (SWCOMPONENTTCRID,ROWIDENTIFIER,CONFIGURATIONITEM,COMPONENTID,AIMSREFERENCE,GENERICVERSION,LOCOSPECIFICDATA,INSTALLEDBY,VERIFIEDBY,VALIDATEDBY,GENERICVERSIONCOLUMNID,LOCOSPECIFICDATACOLUMNID,INSTALLEDBYCOLUMNID,VERIFIEDBYCOLUMNID,VALIDATEDBYCOLUMNID,RESETVALUEONLOCALCHANGE1,RESETVALUEONLOCALCHANGE2,RESETVALUEONLOCALCHANGE3,RESETVALUEONLOCALCHANGE4,RESETVALUEONLOCALCHANGE5,RESETVALUEONGLOBALCHANGE1,RESETVALUEONGLOBALCHANGE2,RESETVALUEONGLOBALCHANGE3,RESETVALUEONGLOBALCHANGE4,RESETVALUEONGLOBALCHANGE5,FORCERESETVALUEONGLOBALCHANGE1,FORCERESETVALUEONGLOBALCHANGE2,FORCERESETVALUEONGLOBALCHANGE3,FORCERESETVALUEONGLOBALCHANGE4,FORCERESETVALUEONGLOBALCHANGE5,TCRVERSION,NEXTVERSION,PREVIOUSVERSION,APPLYGLOBALCHANGES,TCRID) values ('D3A3C84A9A3CD14D90305E4C9F8B2EB5',5,'WiMax Configuration','1091:SW:0','N/A','N/A',null,null,null,null,3,4,5,6,7,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,'04.00',null,'66AC4E3F88E39E4386E25E352B3D8B92',0,'028DBD176836D648B19BD3D423586210');
--------------------------------------------------------
--  DDL for Index PK_EWMS_SWCOMPONENTTCRS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_SWCOMPONENTTCRS" ON "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" ("SWCOMPONENTTCRID", "ROWIDENTIFIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_SWCOMPONENTTCRS
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("SWCOMPONENTTCRID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("ROWIDENTIFIER" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("GENERICVERSIONCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("LOCOSPECIFICDATACOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("INSTALLEDBYCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("VERIFIEDBYCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("VALIDATEDBYCOLUMNID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONLOCALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONLOCALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONLOCALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONLOCALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONLOCALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONGLOBALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONGLOBALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONGLOBALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONGLOBALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("RESETVALUEONGLOBALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("FORCERESETVALUEONGLOBALCHANGE1" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("FORCERESETVALUEONGLOBALCHANGE2" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("FORCERESETVALUEONGLOBALCHANGE3" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("FORCERESETVALUEONGLOBALCHANGE4" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("FORCERESETVALUEONGLOBALCHANGE5" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" MODIFY ("APPLYGLOBALCHANGES" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_SWCOMPONENTTCRS" ADD CONSTRAINT "PK_EWMS_SWCOMPONENTTCRS" PRIMARY KEY ("SWCOMPONENTTCRID", "ROWIDENTIFIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
