--------------------------------------------------------
--  File created - Thursday-May-10-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EWMS_WMSUSERS
--------------------------------------------------------

  CREATE TABLE "AUTOHAUL"."EWMS_WMSUSERS" 
   (	"WMSUSERID" RAW(16), 
	"USERNAME" VARCHAR2(4000 CHAR), 
	"ISSUPERVISOR" NUMBER(1,0), 
	"ISCOMMISSIONING" NUMBER(1,0), 
	"ISCONSTRUCTION" NUMBER(1,0), 
	"ISENABLED" NUMBER(1,0), 
	"PERSONNAME" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into AUTOHAUL.EWMS_WMSUSERS
SET DEFINE OFF;
Insert into AUTOHAUL.EWMS_WMSUSERS (WMSUSERID,USERNAME,ISSUPERVISOR,ISCOMMISSIONING,ISCONSTRUCTION,ISENABLED,PERSONNAME) values ('8F21BB838A6511429C03857F65CFBBE6','9197822',0,0,1,1,'Bradley Osrin');
Insert into AUTOHAUL.EWMS_WMSUSERS (WMSUSERID,USERNAME,ISSUPERVISOR,ISCOMMISSIONING,ISCONSTRUCTION,ISENABLED,PERSONNAME) values ('8258DA3F911565408E6DC5881B1C591F','9200630',0,0,1,1,'Stephen Webber');
Insert into AUTOHAUL.EWMS_WMSUSERS (WMSUSERID,USERNAME,ISSUPERVISOR,ISCOMMISSIONING,ISCONSTRUCTION,ISENABLED,PERSONNAME) values ('BAB8A6F1523D484A8E6E12285D62A061','9085909',1,1,1,1,'Cara Gleave');
--------------------------------------------------------
--  DDL for Index PK_EWMS_WMSUSERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTOHAUL"."PK_EWMS_WMSUSERS" ON "AUTOHAUL"."EWMS_WMSUSERS" ("WMSUSERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EWMS_WMSUSERS
--------------------------------------------------------

  ALTER TABLE "AUTOHAUL"."EWMS_WMSUSERS" MODIFY ("WMSUSERID" NOT NULL ENABLE);
  ALTER TABLE "AUTOHAUL"."EWMS_WMSUSERS" ADD CONSTRAINT "PK_EWMS_WMSUSERS" PRIMARY KEY ("WMSUSERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
