name: Create Branch on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: check the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: create a branch for the issue
      - name: Create a branch for the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # extract issue number and title
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          ISSUE_TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH" | tr ' ' '-')
          
          # make sure the branch name is valid
          BRANCH_NAME="Branch-issue-${ISSUE_NUMBER}-${ISSUE_TITLE}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')
          
          # define default branch
          DEFAULT_BRANCH="main"
          git fetch origin
          git checkout -b "$BRANCH_NAME" "origin/$DEFAULT_BRANCH"
          git push origin "$BRANCH_NAME"

          echo "Branch '$BRANCH_NAME' has been created and pushed to origin."

      # Step 3: add comments to Issue
      - name: Add a comment to the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")
          ISSUE_TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH" | tr ' ' '-')
          BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')

          ISSUE_URL=$(jq -r '.issue.url' "$GITHUB_EVENT_PATH")
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"Branch '$BRANCH_NAME' has been created.\"}" \
            "$ISSUE_URL/comments"
